### ISSUE TITLE
How to use Wireshark to look at the communication between the phone and the drone.

### ISSUE THREAD

**Issue by johnteoh90** [markszabo/drone-hacking#2]
Hi, sorry I am newbie here who is trying to understand the usage of wireshark. However, I am keen to learn to know how can I use the wireshark installed in my laptop to look at the connection between the drone and phone? 

Is it through the use of FTP that was mentioned in your README?

**Comment by johnteoh90** [comment]
By the way your approach is it possible to be done in windows platform?

**Comment by markszabo** [comment]
Hi @johnteoh90,

Yes, what I did is possible on Windows. You should install python and scapy as described [here](https://scapy.readthedocs.io/en/latest/installation.html#windows), and it should work.

About wireshark: if you connect to the drone's wifi network with your laptop and there is no password on the wifi (this is the case by default), then you should be able to capture the traffic between the phone and the drone with the Wireshark running on your laptop. Make sure you enable [promiscuous mode](https://wiki.wireshark.org/CaptureSetup/WLAN#Promiscuous_mode). 

If it doesn't work, the driver of your wifi card might not support it. Then either try a USB wifi adapter (if you have one), or capture the traffic on the phone and then analyze it on your laptop. On capturing traffic on the phone see this thread: https://stackoverflow.com/a/9570093

Let me know how it goes,
Mark

**Comment by johnteoh90** [comment]
Hey Mark thanks for the Tip! Will try it out and let you know the outcome! Thanks again!

**Comment by Dionysis3** [comment]
I am also trying to packet-capture with wireshark my drone. It seems it creates a subnet for my phone (172.16.152.171) when connected with the app. But when i try to ping and eventually sniff the traffic the before mentioned ip is unreachable.  
I copy paste ip route command so as you to have more clues.
$$ ip route
default via 172.16.10.1 dev wlp6s0 proto static metric 20600 
169.254.0.0/16 dev wlp6s0 scope link metric 1000 
172.16.0.0/16 dev wlp6s0 proto kernel scope link src 172.16.10.2 metric 600 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.56.0/24 dev vboxnet0 proto kernel scope link src 192.168.56.1 linkdown   
Any ideas???
