### ISSUE TITLE
Lightbridge and OcuSync protocol description

### ISSUE THREAD

**Issue by kostaov** [markszabo/drone-hacking#4]
Hi,
I need a protocol description similar to MAVLink (https://arxiv.org/pdf/1906.10641.pdf) for DJI Lightbridge 1,2; OcuSync 1,2,3 only.
This description should contain the frame structure and a description of all types of transmitted messages and their fields.

Can anyone help me?

**Comment by markszabo** [comment]
I'm sorry, I've never worked with DJIs
